FROM quay.io/keycloak/keycloak:24.0 as builder

COPY target/keycloak-age-validator-1.0-0.jar /opt/keycloak/providers/
COPY themes/custom /opt/keycloak/themes/custom

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:24.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/